logs:
  logs_path: 'logs/'

data:
  iemocap_data_path: "../data/IEMOCAP_full_release/"

  preprocessed_data_path: "../data/preprocessed_data/"
  enterfece_data_path: "../data/enterface_database/"
  ravdess_data_path: '../data/RAVDESS'
  iemocap_cliped_video_path: '../data/iemocap/'

  save_test_data_path: "../data/preprocessed_data/test_data/"
  save_train_data_path: "../data/preprocessed_data/train_data/"
  test_paths: "../data/preprocessed_data/filtered_emotions_paths/test_paths.csv"
  train_paths: "../data/preprocessed_data/filtered_emotions_paths/train_paths.csv"

  train_pkl: '../data/preprocessed_data/train_pkl.pkl'
  test_pkl: '../data/preprocessed_data/test_pkl.pkl'

  save_test_name: 'final_test_paths.csv'
  save_train_name: 'final_train_paths.csv'
  filtered_save_path: '../data/preprocessed_data/filtered_emotions_paths/'

  train_xp: '../data/preprocessed_data/train_data/train_x.npy'
  train_yp: '../data/preprocessed_data/train_data/train_y.npy'
  test_xp: '../data/preprocessed_data/train_data/test_x.npy'
  test_yp: '../data/preprocessed_data/train_data/test_y.npy'