logs:
  logs_path: 'logs/'

data:
  train_xp: '../data/preprocessed_data/train_data/train_x.npy'
  train_yp: '../data/preprocessed_data/train_data/train_y.npy'
  test_xp: '../data/preprocessed_data/train_data/test_x.npy'
  test_yp: '../data/preprocessed_data/train_data/test_y.npy'